[tool.poetry]
name = "cartpoleml"
version = "0.1.0"
description = "Machine Learning of Inverted Pendula"
authors = ["Jeppe Klitgaard <jk782@cam.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
gym = "^0.18.3"
torch = "^1.9.0"
torchvision = "^0.10.0"
torchaudio = "^0.9.0"
jupyterlab = "^3.0.16"
matplotlib = "^3.4.2"
Pillow = "^8.2.0"
numpy = "^1.21.0"

[tool.poetry.dev-dependencies]
jupytext = "^1.11.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
